version: "3"

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/code
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  nginx:
    build: ./project/nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web
    restart: "on-failure"


volumes:
  postgres_data:
  static_volume:
  media_volume:

